### ISSUE TITLE
Candidate disappears

### ISSUE THREAD

**Issue by taise** [highwide/voterm#1]
"コンパイラ" was disappeared.

![screencapture-voterm-herokuapp-votes-2-1503924209073](https://user-images.githubusercontent.com/934202/29773873-501003ec-8c3a-11e7-86cd-b8fca937f385.png)

![screencapture-voterm-herokuapp-results-4-1503924232149](https://user-images.githubusercontent.com/934202/29773884-5a32dcb4-8c3a-11e7-9168-44dcb991d1fa.png)

**Comment by highwide** [comment]
Thank you for reporting a issue, @taise !
I guess it's not a bug.

A count of candidacy in a vote is not equal to count of round in this vote.
In your screenshot's case, the 37th round includes "Loser: コンパイラ".
But it's not appear in the current spec.

I know it's not user friendly UI. So, I'll fix it.

**Comment by highwide** [comment]
Resolve #2

**Comment by taise** [comment]
![thx](http://media0.giphy.com/media/Kz1ha1Jc4ymKk/giphy.gif)
